# Generated by Django 3.1.7 on 2021-11-06 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_auto_20210402_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisitions',
            name='creationDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
